only_rules:
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - mark
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - nsobject_prefer_isequal
  - opening_brace
  - operator_whitespace
  - orphaned_doc_comment
  - overridden_super_call
  - private_action
  - private_outlet
  - private_over_fileprivate
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - self_in_property_initialization
  - shorthand_operator
  - sorted_first_last
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  # - todo
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - xctfail_message

excluded:
  - .derivedData/
  - .build/
  - DerivedData/
  - tools/
  - utils/
  - swift-playground/

identifier_name:
  max_length: 60
  excluded:
    - id

line_length:
  warning: 150
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
function_body_length:
  warning: 300
  error: 300
function_parameter_count:
  warning: 8
  error: 8
type_body_length:
  warning: 500
  error: 500
file_length:
  warning: 800
  error: 800
  ignore_comment_only_lines: true
large_tuple:
  - 3
  - 4
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 15
  error: 25
reporter: "xcode"
nesting:
  type_level: 3
multiple_closures_with_trailing_closure: error
orphaned_doc_comment: error

custom_rules:
  describe_assert_false:
    name: "Avoid empty assert 'false'"
    regex: 'assert\(false\)'
    message: 'Use assert(false, "description") instead.'
    severity: error
  describe_assertionFailure:
    name: "Avoid empty assertionFailure"
    regex: 'assertionFailure\(\)'
    message: 'Use assertionFailure("description") instead.'
    severity: error
  describe_precondition_false:
    name: "Avoid empty precondition 'false'"
    regex: 'precondition\(false\)'
    message: 'Use precondition(false, "description") instead.'
    severity: error
  describe_preconditionFailure:
    name: "Avoid empty preconditionFailure"
    regex: 'preconditionFailure\(\)'
    message: 'Use preconditionFailure("description") instead.'
    severity: error
  describe_fatalError:
    name: "Avoid empty fatalError"
    regex: 'fatalError\(\)'
    message: 'Use fatalError("description") instead.'
    severity: error
  avoiding_lightweight_assert:
    name: "Avoid lightweight assert"
    regex: 'assert\('
    message: "avoid assert; use XCTAssert (tests) or assertionFailure, precondition, preconditionFailure, or fatalError."
    severity: error
  