filter_results:
- ApplicationFramework

locations:
  output_directory_html: HTMLReport/
  output_directory_json: CodeCoverage/

excluded:
  files:
    - *ViewController.swift
  functions:
    - deinit
  targets:
    - Adyen.bundle
    - Adyen.framework
    - AdyenActions.bundle
    - AdyenCard.bundle
    - AdyenNetworking.framework
    - Apollo.framework
    - AppCenterDistributeResources.bundle
    - ApplicationFramework.app
    - Auth0.framework
    - CocoaMQTT.framework
    - Collar.bundle
    - Collar.framework
    - GoogleMapsUtils.framework
    - JOSESwift.framework
    - JTAppleCalendar.framework
    - JWTDecode.framework
    - Lottie.framework
    - MyPorschePersistenceTestsHostApp.app
    - OHHTTPStubs.framework
    - ObjcExceptionBridging.framework
    - PhoneNumberKit.framework
    - Pods_ApplicationFramework.framework
    - Pods_PAFAddVehicle.framework
    - Pods_PAFAddVehicle_AddVehicleTests.framework
    - Pods_PAFAppServices.framework
    - Pods_PAFAppServices_AppServicesTests.framework
    - Pods_PAFBDUI.framework
    - Pods_PAFBDUI_BDUITests.framework
    - Pods_PAFBooking.framework
    - Pods_PAFBooking_BookingTests.framework
    - Pods_PAFBusinessAsterixCN.framework
    - Pods_PAFBusinessAsterixCN_BusinessAsterixCNTests.framework
    - Pods_PAFBusinessPortfolioCN.framework
    - Pods_PAFBusinessPortfolioCN_BusinessPortfolioCNTests.framework
    - Pods_PAFCarPlayAutomaker.framework
    - Pods_PAFCarPlayAutomakerService.framework
    - Pods_PAFCarPlayAutomakerService_CarPlayAutomakerServiceTests.framework
    - Pods_PAFCarPlayAutomaker_CarPlayAutomakerTests.framework
    - Pods_PAFChargingCN.framework
    - Pods_PAFChargingCN_ChargingCNTests.framework
    - Pods_PAFChargingCore.framework
    - Pods_PAFChargingCore_ChargingCoreTests.framework
    - Pods_PAFChargingData.framework
    - Pods_PAFChargingData_ChargingDataTests.framework
    - Pods_PAFChargingPresentation.framework
    - Pods_PAFChargingPresentation_ChargingPresentationTests.framework
    - Pods_PAFChinaServices.framework
    - Pods_PAFChinaServices_ChinaServicesTests.framework
    - Pods_PAFCommon.framework
    - Pods_PAFCommonXCTest.framework
    - Pods_PAFCommon_CommonTests.framework
    - Pods_PAFConnect.framework
    - Pods_PAFConnectStoreService.framework
    - Pods_PAFConnectStoreService_ConnectStoreServiceTests.framework
    - Pods_PAFConnect_ConnectTests.framework
    - Pods_PAFCustomerRelationCN.framework
    - Pods_PAFCustomerRelationCN_CustomerRelationCNTests.framework
    - Pods_PAFDealerCore.framework
    - Pods_PAFDealerService.framework
    - Pods_PAFDealerService_DealerServiceTests.framework
    - Pods_PAFDirectCommunication.framework
    - Pods_PAFDirectCommunication_DirectCommunicationTests.framework
    - Pods_PAFDiscover.framework
    - Pods_PAFDiscoverServices.framework
    - Pods_PAFDiscoverServices_DiscoverServicesTests.framework
    - Pods_PAFDiscover_DiscoverTests.framework
    - Pods_PAFFleetAgent.framework
    - Pods_PAFFleetAgent_FleetAgentTests.framework
    - Pods_PAFGSDKLogger.framework
    - Pods_PAFHomeChargingCore.framework
    - Pods_PAFHomeChargingCore_HomeChargingCoreTests.framework
    - Pods_PAFHomeChargingData.framework
    - Pods_PAFHomeChargingData_HomeChargingDataTests.framework
    - Pods_PAFHomeChargingPresentation.framework
    - Pods_PAFHomeChargingPresentation_HomeChargingPresentationTests.framework
    - Pods_PAFLiveChatCN.framework
    - Pods_PAFLiveChatCN_LiveChatCNTests.framework
    - Pods_PAFMap.framework
    - Pods_PAFMapCN.framework
    - Pods_PAFMapCN_MapCNTests.framework
    - Pods_PAFMapService.framework
    - Pods_PAFMapService_MapServiceTests.framework
    - Pods_PAFMap_MapTests.framework
    - Pods_PAFMessageCenterCN.framework
    - Pods_PAFMessageCenterCN_MessageCenterCNTests.framework
    - Pods_PAFMockBff.framework
    - Pods_PAFMockBffService.framework
    - Pods_PAFMockBffService_MockBffServiceTests.framework
    - Pods_PAFMockBff_MockBffTests.framework
    - Pods_PAFMyPorsche.framework
    - Pods_PAFMyPorscheCN.framework
    - Pods_PAFMyPorscheCN_MyPorscheCNTests.framework
    - Pods_PAFMyPorsche_MyPorschePersistenceTests.framework
    - Pods_PAFMyPorsche_MyPorschePersistenceTestsHostApp.framework
    - Pods_PAFMyPorsche_MyPorscheTests.framework
    - Pods_PAFNativeRegistration.framework
    - Pods_PAFNativeRegistrationService.framework
    - Pods_PAFNativeRegistrationService_NativeRegistrationServiceTests.framework
    - Pods_PAFNativeRegistration_NativeRegistrationTests.framework
    - Pods_PAFNetwork.framework
    - Pods_PAFNetwork_NetworkTests.framework
    - Pods_PAFPCM.framework
    - Pods_PAFPCM_PCMTests.framework
    - Pods_PAFPOIFavorites.framework
    - Pods_PAFPOIFavorites_POIFavoritesTests.framework
    - Pods_PAFPOIManagementService.framework
    - Pods_PAFPOIManagementService_POIManagementServiceTests.framework
    - Pods_PAFPOISyncService.framework
    - Pods_PAFPOISyncService_POISyncServiceTests.framework
    - Pods_PAFPaymentServiceCN.framework
    - Pods_PAFPaymentServiceCN_PaymentServiceCNTests.framework
    - Pods_PAFPersistence.framework
    - Pods_PAFPostCN.framework
    - Pods_PAFPostCN_PostCNTests.framework
    - Pods_PAFQRCodeLogin.framework
    - Pods_PAFQRCodeLogin_QRCodeLoginTests.framework
    - Pods_PAFRHMIService.framework
    - Pods_PAFRHMIService_RHMIServiceTests.framework
    - Pods_PAFRemoteParkAssistant.framework
    - Pods_PAFRemoteParkAssistantService.framework
    - Pods_PAFRemoteParkAssistant_RemoteParkAssistantTests.framework
    - Pods_PAFRoadsideAssistance.framework
    - Pods_PAFRoadsideAssistance_RoadsideAssistanceTests.framework
    - Pods_PAFRoutingCore.framework
    - Pods_PAFRoutingCore_RoutingCoreTests.framework
    - Pods_PAFRoutingService.framework
    - Pods_PAFRoutingService_RoutingServiceTests.framework
    - Pods_PAFScaffold.framework
    - Pods_PAFScaffold_ScaffoldTests.framework
    - Pods_PAFShareExtensionKit.framework
    - Pods_PAFSubscription.framework
    - Pods_PAFSubscriptionService.framework
    - Pods_PAFSubscriptionService_SubscriptionServiceTests.framework
    - Pods_PAFSubscription_SubscriptionTests.framework
    - Pods_PAFTrackYourDream.framework
    - Pods_PAFTrackYourDream_TrackYourDreamTests.framework
    - Pods_PAFUIAnimations.framework
    - Pods_PAFUIAnimations_UIAnimationsTests.framework
    - Pods_PAFUIComponents.framework
    - Pods_PAFUIComponents_UIComponentsTests.framework
    - Pods_PAFUser.framework
    - Pods_PAFUserManual.framework
    - Pods_PAFUserManual_UserManualTests.framework
    - Pods_PAFUser_UserTests.framework
    - Pods_PAFVehicle.framework
    - Pods_PAFVehicleCN.framework
    - Pods_PAFVehicleCN_VehicleCNTests.framework
    - Pods_PAFVehicleOrder.framework
    - Pods_PAFVehicleOrderService.framework
    - Pods_PAFVehicleOrderServiceCore.framework
    - Pods_PAFVehicleOrderService_VehicleOrderServiceTests.framework
    - Pods_PAFVehicleOrder_VehicleOrderTests.framework
    - Pods_PAFVehicle_VehicleTests.framework
    - Pods_PAFWelfareCN.framework
    - Pods_PAFWelfareCN_WelfareCNTests.framework
    - SLPaymentSDK.framework
    - SLPaymentSDKResources.bundle
    - SimpleKeychain.framework
    - SnapshotTesting.framework
    - SubscriptionTests.xctest
    - SwiftKeychainWrapper.framework
    - TrustKit.framework
    - XCGLogger.framework
    - ZIPFoundation.framework
