name: "Sign and Notarize macOS Executable"
description: "Signs, notarizes, and staples a macOS executable using Apple Developer credentials."
author: "arconsis"

runs:
  using: "composite"
  steps:
    - name: Codesign executable
      env:
        MACOS_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE_P12 }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
        security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
        IDENTITY=$(security find-identity -v | grep -o '^[^ ]*')
        /usr/bin/codesign --force -s $IDENTITY "${{ inputs.executable }}" -v
inputs:
  executable:
    description: "Path to the executable to sign."
    required: true
