name: "Sign and Notarize macOS Executable"
description: "Signs, notarizes, and staples a macOS executable using Apple Developer credentials."
author: "arconsis"

runs:
  using: "composite"
  steps:
    - name: Codesign executable
      shell: bash
      env:
        MACOS_CERTIFICATE: ${{ inputs.certificate_p12 }}
      run: echo $MACOS_CERTIFICATE | base64 —d > certificate.p12

    - name: Codesign executable
      shell: bash
      env:
        KEYCHAIN_PASSWORD: ${{ inputs.keychain_pwd }}
      run: |
        security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security default-keychain -s build.keychain
    - name: Codesign executable
      shell: bash
      env:
        MACOS_CERTIFICATE_PWD: ${{ inputs.certificate_pwd }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain_pwd }}
      run: |
        security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
    - name: Codesign executable
      shell: bash
      env:
        EXECUTABLE: ${{ inputs.executable }}
      run: |
        IDENTITY=$(security find-identity -v | grep -o '^[^ ]*')
        /usr/bin/codesign --force -s $IDENTITY "$EXECUTABLE" -v
inputs:
  executable:
    description: "Path to the executable to sign."
    required: true
  certificate_p12:
    description: "Base64 encoded .p12 certificate."
    required: true
  certificate_pwd:
    description: "Password for the .p12 certificate."
    required: true
  keychain_pwd:
    description: "Password for the keychain."
    required: true
