name: "Next release version"
description: "This action will generate the next release version according to the release-type"

inputs:
  release-type:
    description: "Should be one of the following: major, minor, patch"
    required: true
outputs:
  release-version:
    description: "Calculated Next Release Version"
    value: ${{ steps.release-version.outputs.release }}
  current-version:
    description: "Receive current Version"
    value: ${{ steps.last-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: git checkout
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Calculate next release version
      id: release-version
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint && ${{ github.action_path }}/entrypoint "${{ inputs.release-type }}"
