name: "Detect swift version"
description: "use the Package.swift file to determine the correct swift version"

outputs:
  swift-version:
    description: "Calculated Next Release Version"
    value: ${{ jobs.get-swift-version.outputs.swift-version }}

runs:
  using: composite
  steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: Extract Swift version from Package.swift
      id: determine-swift-version
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift
