name: "Detect swift version"
description: "use the Package.swift file to determine the correct swift version"

outputs:
  swift-version:
    description: "Calculated Next Release Version"
    value: ${{ jobs.get-swift-version.outputs.swift-version }}

runs:
  using: composite
  steps:
    - name: git checkout
      uses: actions/checkout@v4

    - name: extract first line from Package.swift
      id: package-swift-first-line
      shell: bash
      run: echo "first_line=$(head -n 1 Package.swift)" >> $GITHUB_OUTPUT

    - name: extract first line from Package.swift
      id: determine-swift-version
      shell: bash
      run: |
        if [[ "${{ steps.package-swift-first-line.outputs.first_line }}" =~ //\ swift-tools-version:\ ([0-9]+\.[0-9]+(\.[0-9]+)?) ]]; then
          echo "swift-version=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT" 
          echo "Swift ${BASH_REMATCH[1]} Detected" >> $GITHUB_STEP_SUMMARY
        else
          exit 1
        fi
