name: "[job] Branch"

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      is-reverting:
        required: false
        type: boolean

jobs:
  create-release-branch:
    name: "Creation"
    if: ${{ inputs.is-reverting == '' || inputs.is-reverting == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: create branch (releases/${{ inputs.release-version }})
        run: git branch releases/${{ inputs.release-version }}

      - name: checkout branch (releases/${{ inputs.release-version }})
        run: git checkout releases/${{ inputs.release-version }}

      - name: publish branch (releases/${{ inputs.release-version }})
        run: git push --set-upstream origin releases/${{ inputs.release-version }}

      - name: update version-file
        run: |
          echo ${{ inputs.release-version }} > .version

      - name: update version in app
        working-directory: ./Sources/App/
        run: |
          sed "s#version: \".*\"#version: \"${{ inputs.release-version }}\"#" "App.swift" >> new_App.swift
          rm ./App.swift
          mv ./new_App.swift ./App.swift

      - name: git status after cahnges
        run: git status

      - name: commit bumped version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[BOT] update App version to ${{ inputs.release-version }}"
          commit_user_name: "github-release[bot]"
          commit_user_email: github.release@elmoritz.eu
          commit_author: Moritz Ellerbrock <github@elmoritz.eu>

      - name: onFailure delete branch
        if: failure()
        run: |
          echo "# ABORT: New release will be stopped" >> $GITHUB_STEP_SUMMARY
          git push origin --delete releases/${{ inputs.release-version }} || true
          echo "New release branch (releases/${{ inputs.release-version }}) was deleted" >> $GITHUB_STEP_SUMMARY

  deleting-release-branch:
    name: Create release branch
    if: ${{ inputs.is-reverting == true }}
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: delete release\${{ inputs.release-version }}
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: releases/${{ inputs.release-version }}
