name: "Create a new release branch"
description: "This action will create a new branch for the current release and delete it if something goes wrong"

inputs:
  release-version:
    required: true
    description: "string formatted version number for the next release"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Create release branch and bump version
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint
        ${{ github.action_path }}/entrypoint.swift "${{ inputs.release-version }}"
