name: "Sign and Notarize macOS Executable"
description: "Signs, notarizes, and staples a macOS executable using Apple Developer credentials."
author: "arconsis"

inputs:
  tool_name:
    description: "Name of the executable to sign and notarize."
    required: true
  developer_identity:
    description: "Developer ID Application identity string."
    required: true

runs:
  using: "composite"
  steps:
    - name: Run sign Swift script
      run: |
        chmod +x ${{ github.action_path }}/sign.swift
        chmod +x ${{ github.action_path }}/notarize.swift
        ${{ github.action_path }}/sign.swift
        if [ "${{ inputs.notarize }}" = "true" ]; then
          TOOL_NAME="${{ inputs.tool_name }}" \
          APPLE_ID="${{ inputs.apple_id }}" \
          TEAMID="${{ inputs.teamid }}" \
          APPLE_APP_SPECIFIC_PASSWORD="${{ inputs.apple_app_specific_password }}" \
          PRODUCT_PATH="${{ inputs.product_path }}" \
          ${{ github.action_path }}/notarize.swift
        fi
      shell: bash
      env:
        PRODUCT_PATH: ${{ inputs.product_path }}
        DEVELOPER_IDENTITY: ${{ inputs.developer_identity }}
        P12_BASE64: ${{ secrets.DEVELOPER_ID_P12_BASE64 }}
        P12_PASSWORD: ${{ secrets.DEVELOPER_ID_P12_PASSWORD }}
        TOOL_NAME: ${{ inputs.tool_name }}
