name: "Sign and Notarize macOS Executable"
description: "Signs, notarizes, and staples a macOS executable using Apple Developer credentials."
author: "arconsis"
runs:
  using: "composite"
  steps:
    - name: Run sign and notarize script
      shell: bash
      run:
        chmod +x ${{ github.action_path }}/entrypoint.swift && ${{ github.action_path }}/entrypoint.swift \
        --executable "${{ inputs.executable }}" \
        --identity "${{ inputs.apple_signing_identity }}" \
        --apple_id "${{ inputs.apple_id }}" \
        --team_id "${{ inputs.apple_team_id }}" \
        --password "${{ inputs.apple_app_specific_password }}"
inputs:
  executable:
    description: "Path to the executable to sign and notarize."
    required: true
  apple_signing_identity:
    description: "Apple code signing identity."
    required: true
  apple_id:
    description: "Apple ID for notarization."
    required: true
  apple_team_id:
    description: "Apple Developer Team ID."
    required: true
  apple_app_specific_password:
    description: "App-specific password for notarization."
    required: true
