name: "Sign macOS Executable"
description: "Signs a macOS executable using Apple Developer credentials."
author: "arconsis"

runs:
  using: "composite"
  steps:
    - name: Codesign executable
      shell: bash
      env:
        MACOS_CERTIFICATE: ${{ inputs.certificate_p12 }}
        MACOS_CERTIFICATE_PWD: ${{ inputs.certificate_pwd }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain_pwd }}
        EXECUTABLE: ${{ inputs.executable }}
      run: |
        xattr -l "$EXECUTABLE"
        echo $MACOS_CERTIFICATE | base64 --decode -o certificate.p12
        security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
        echo "Available code signing identities in build.keychain:"
        IDENTITY_HASH=$(security find-identity -v -p codesigning build.keychain | awk '/Developer ID Application/ {print $2}')
        echo "Using identity hash: $IDENTITY_HASH"
        /usr/bin/codesign --force -s "$IDENTITY_HASH" "$EXECUTABLE" -v

inputs:
  executable:
    description: "Path to the executable to sign."
    required: true
  certificate_p12:
    description: "Base64 encoded .p12 certificate."
    required: true
  certificate_pwd:
    description: "Password for the .p12 certificate."
    required: true
  keychain_pwd:
    description: "Password for the keychain."
    required: true
